### ISSUE TITLE
Please add BAT as value for RFLinkData device

### ISSUE THREAD

**Issue by Redferne** [sirchia/pimatic-rflink#11]
Example device:

20;39;AlectoV3;ID=00a7;TEMP=80c0;HUM=3d;BAT=OK;"

Values should be one of: temp, hum, baro, hstatus, uv, lux, rain, raintot, winsp, awinsp, wings, windir, winchl, wintmp, co2, sound, kwatt, watt, dist, meter, volt, current

**Comment by sirchia** [comment]
Thanks for reporting this issue.
I pushed some changes that should fix it, but I don't have the necessary devices to test it out.
Can you try out the current master branch to see if the issue is fixed and post your results here.
I will make a new release if the tests are successful.

**Comment by Redferne** [comment]
How do I pull from master?

`sudo npm install https://github.com/sirchia/pimatic-rflink.git`

Results in errors installing serialport:

```
> serialport@2.0.6 install /home/pi/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport
> node-pre-gyp install --fallback-to-build
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.4.5"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/.node-gyp"
make: Entering directory '/home/pi/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/build'
make: *** No rule to make target '../.node-gyp/4.4.5/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/home/pi/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.14-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pi/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/build/Release/node-v46-linux-arm/serialport.node" "--module_name=serialport" "--module_path=/home/pi/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/build/Release/node-v46-linux-arm"
gyp ERR! cwd /home/pi/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/build/Release/node-v46-linux-arm/serialport.node --module_name=serialport --module_path=/home/pi/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/build/Release/node-v46-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.4.14-v7+
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/pi/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport
node-pre-gyp ERR! node -v v4.4.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.18
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/build/Release/node-v46-linux-arm/serialport.node --module_name=serialport --module_path=/home/pi/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/build/Release/node-v46-linux-arm' (1)
npm ERR! Linux 4.4.14-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "git://github.com/sirchia/pimatic-rflink.git"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! serialport@2.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@2.0.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs serialport
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.
```

**Comment by sirchia** [comment]
I just tried the following which seemed to work:
in the root of pimatic installation dir run:
# **npm install sirchia/pimatic-rflink**

I'm running the following versions, maybe that has some influence:
# npm -v
3.5.3
# node -v
v4.2.6

**Comment by Redferne** [comment]
Latest @master works perfectly. Thank you!

**Comment by sirchia** [comment]
Issue closed. 
Bugfix in release 0.6.0
