### ISSUE TITLE
Receiving new dimmer value causes crash

### ISSUE THREAD

**Issue by Redferne** [sirchia/pimatic-rflink#12]
When a dimmer device is set externally (using original remote) this causes crash below:

---

warn [pimatic]: Keeping pimatic alive, but could be in an undefined state, please restart pimatic as soon as possible!
22:26:53error [pimatic]: A uncaught exception occured: AssertionError: false == true
    at RFLinkDimmer.DimmerActuator._setDimlevel (/home/pi/pimatic-app/node_modules/pimatic/lib/devices.coffee:358:7)
    at RFLinkDimmer._setDimlevel (/home/pi/pimatic-app/node_modules/pimatic/lib/devices.coffee:1:1)
    at Board.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-rflink/rflink.coffee:204:18)
    at emitOne (events.js:82:20)
    at Board.emit (events.js:169:7)
    at Board._processData (/home/pi/pimatic-app/node_modules/pimatic-rflink/lib/board.coffee:129:11)
    at SerialPortDriver.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-rflink/lib/board.coffee:43:8)
    at emitOne (events.js:77:13)
    at SerialPortDriver.emit (events.js:169:7)
    at SerialPort.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-rflink/lib/serialport.coffee:37:8)
    at emitOne (events.js:77:13)
    at SerialPort.emit (events.js:169:7)
    at /home/pi/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/parsers.js:25:17
    at Array.forEach (native)
    at Object.parser (/home/pi/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/parsers.js:24:13)
    at Object.SerialPort.opts.dataCallback (/home/pi/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/serialport.js:181:12)
    at SerialPortFactory.SerialPort._emitData (/home/pi/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/serialport.js:396:20)
    at afterRead (/home/pi/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/serialport.js:372:20)
    at /home/pi/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/serialport.js:388:9
    at FSReqWrap.wrapper [as oncomplete](fs.js:576:17)
 This is most probably a bug in pimatic or in a module, please report it!

**Comment by sirchia** [comment]
Thanks for reporting this issue.
I pushed some changes that should fix it, but I don't have the necessary devices to test it out.
Can you try out the current master branch to see if the issue is fixed and post your results here.
I will make a new release if the tests are successful.

**Comment by Redferne** [comment]
Latest @master works perfectly. Thank you!

**Comment by sirchia** [comment]
Issue closed. 
Bugfix in release 0.6.0
